name: Docker Image CI

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag internship-parser
  
  deploy:

    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TG_API_TOKEN: ${{ secrets.TG_API_TOKEN }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key
          chmod 600 ./key
          eval $(ssh-agent)
          ssh-add ./key
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd WBParser
            git checkout master
            git pull
            docker build -t internship-parser .
            docker kill  internship-parser-container
            docker rm internship-parser-container
            docker run --name internship-parser-container -v $(pwd):/parser/ -e TG_API_TOKEN=${{ secrets.TG_API_TOKEN }} -d internship-parser
          EOF
